version: '3'
networks:
  app-net:
    driver: bridge
services:
  postgres:
    image: 'postgres:17'
    container_name: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interviewer
    ports:
      - "5432:5432"
    networks:
      - app-net
    volumes:
      - ./postgres-data:/var/lib/postgresql/data